### ISSUE TITLE
Requesting to include my package in the Flutter Community

### ISSUE THREAD

**Issue by jaiswalshubham84** [fluttercommunity/community#10]
Hi Flutter Community,

i have created a carousel package that aims to provide smooth carousel experience with multiple configuration options.

The pubspec file is updated as per community norms.

dart pub link: https://pub.dartlang.org/packages/flutter_multi_carousel/ 

git repo link : https://github.com/jaiswalshubham84/flutter-multi-carousel.

will you please include my package in Flutter Community

Regards
Shubham Kumar

**Comment by HidayahShukor** [comment]
May I request package for google map navigation or tutorial to integrate navigation in my application?

**Comment by jeroen-meijer** [comment]
Hi there,

This looks really good. We'll have to do a code review and see what other packages are out there, but we will get back to you.

Thanks for bringing it to our attention.

**Comment by jeroen-meijer** [comment]
Hi there,

Thanks for waiting.
After reviewing, I have a couple of comments.

1. Please add documentation to all the fields in the `Carousel` widget (to `type` for example).
2. It may be best to change both `type` and `indicatorType` to enums. That way, it's more descriptive and users will know what their options are.

Please consider these changes and reply to this issue once you've comitted them or have any other feedback.

**Comment by jeroen-meijer** [comment]
Any updates on this?

**Comment by jeroen-meijer** [comment]
Closing due to lack of reply. Feel free to comment and it can be reopened.
