### ISSUE TITLE
Micro-Frontend   in Flutter Web

### ISSUE THREAD

**Issue by dhanraj-verma** [fluttercommunity/community#109]
# Discussion: Micro-Frontend   in Flutter Web

We are working on a project which has many module with separate functionality. The requirement is that every module work as independent application but the user feels like he is using single application.

## Summary
First we tried using flutter package but it fails because package can not run independently then we go for flutter application.
In our second approach  we have a big question mark that how shall we join all independent flutter web applications.

Any suggestions/solution would be appriciated.

**Comment by dhanraj-verma** [comment]
Any clues, suggestion?

**Comment by PratikBangar84** [comment]
develop it as a thread(instagram) functionality

**Comment by dhanrajvermaRepo** [comment]
> develop it as a thread(instagram) functionality

Can you please provide some more information

**Comment by PratikBangar84** [comment]
api integration will work

**Comment by slightfoot** [comment]
This is not a help general help forum. Please check https://flutter.dev/community
