### ISSUE TITLE
Request for Google Map Navigation Package/Tutorial

### ISSUE THREAD

**Issue by HidayahShukor** [fluttercommunity/community#11]
I wonder if flutter support google map navigation and also best route? If it can be integrate into Flutter, I looking forward for package and tutorial.

Thank you :)

**Comment by jeroen-meijer** [comment]
Hi there,

All the tutorials and other articles are on [https://medium.com/flutter-community](Flutter Community's Medium publication page (https://medium.com/flutter-community)).
There is already an official Google Maps plugin that's still being worked on. Check it out here: https://pub.dartlang.org/packages/google_maps_flutter

Hope this helped.
Closing.
