### ISSUE TITLE
Package Proposal: wakelock

### ISSUE THREAD

**Issue by diegotori** [fluttercommunity/community#123]
# Package Proposal: wakelock

**Dependency name (as used in *pubspec.yaml*):** wakelock
**Current pub.dev link:** https://pub.dev/packages/wakelock
**Current Git repository link:** https://github.com/creativecreatorormaybenot/wakelock
**Description:** A Flutter plugin that allows you to keep the device screen awake, i.e. prevent the screen from sleeping.
**Current maintainer:** creativecreatorormaybenot, creativecreatorormaybenot@gmail.com, @creativecreatorormaybenot
**Needs new maintainer after transfer:** YES
**New maintainer (if applicable):** Diego Tori, diegotoridoesandroid@gmail.com, @diegotori
**Reason for transfer:** According to this [PR](https://github.com/creativecreatorormaybenot/wakelock/pull/203), the original maintainer may not be available to maintain this plugin for the foreseeable future.
**Comments:** Note that I'm posting this as a proposal to preserve the work of the original author of this package, @creativecreatorormaybenot

**Comment by diegotori** [comment]
Also pinging @mhadaily and @nilsreichardt, the latter of which is in constant contact with the original author of this plugin.

Thanks in advance.

**Comment by vbuberen** [comment]
I will be also available as maintainer if needed in case there is an agreement on moving the package here.

**Comment by madatr** [comment]
interested in using this

**Comment by mashedbymachines** [comment]
Just asking, what is the prgoress of this package transfer?

**Comment by diegotori** [comment]
[wakelock_plus](https://pub.dev/packages/wakelock_plus) is now live on pub.dev.

In other words, wakelock is back on the menu.

**Comment by diegotori** [comment]
@slightfoot I think we can close this, since `wakelock_plus` now exists.
