### ISSUE TITLE
Package Proposal: arcgis_map

### ISSUE THREAD

**Issue by passsy** [fluttercommunity/community#134]
# Package Proposal: arcgis_map

https://developers.arcgis.com/documentation/mapping-apis-and-services/apis-and-sdks/

**Dependency name (as used in *pubspec.yaml*):** not yet published
**Current Git repository link:** private
**Description:** Esri ArcGIS Flutter map package for Android, iOS and Web
**Current maintainer:** Matthaios Saitakis @MatthaiosSait, Stefan Schaller @stefanschaller, Julian Bissekkou @JulianBissekkou, Pascal Welsch @passsy 
**Needs new maintainer after transfer:** No
**Reason for transfer:** Two agencies from Germany, @phntmxyz and @tappeddev, joined forces to bring the popular arcgis map to Flutter. We want to publish it together under a neutral umbrella

**Comment by Dragos16Dohotaru** [comment]
name: arcgis_map
description: Esri ArcGIS Flutter map package for Android, iOS, and Web

# Add this when the package is published
# version: x.x.x

# Other metadata
author: 
  name: phntmxyz and tappeddev
  email: [contact email]

# URL to the homepage of the package
homepage: [package homepage URL]

# URL to the repository on GitHub
repository: 
  type: git
  url: [repository URL]

# License of the package
license: [license]

# Short description of the package
summary: |
  Esri ArcGIS Flutter map package for Android, iOS, and Web.

# Longer description of the package
description: >
  This package provides Flutter developers with a seamless integration of Esri ArcGIS maps into their applications. It supports Android, iOS, and Web platforms, offering a unified and efficient mapping solution.

# List of maintainers
maintainers:
  - name: phntmxyz
    email: [phntmxyz email]
  - name: tappeddev
    email: [tappeddev email]

# Dependency declaration
# dependencies:
#   arcgis_map: x.x.x

# Example usage
# Example:
# ```dart
# import 'package:arcgis_map/arcgis_map.dart';
# ```

# Other relevant information
Replace the placeholders such as [contact email], [package homepage URL], [repository URL], [license], [phntmxyz email], and [tappeddev email] with the actual information.

**Comment by passsy** [comment]
Transfer completed
