### ISSUE TITLE
Article: Platform channel with Protobuf

### ISSUE THREAD

**Issue by truongsinh** [fluttercommunity/community#14]
I would propose to write an article about Platform channel with Protobuf. Abstract:

When writing platform-specific code as Flutter plugins, one of the key things is data transfer between Dart side and platform side. Under the hood, it's just a bunch of binary 0s and 1s. Though all the codes we're dealing with (Dart, Java/Kotlin, ObjC/Swift) is typed, so Flutter makes it easier to have some typing. However, when dealing with complex structure, we will defintely go with `Map`/`List`, and here comes the provlems:
- Casting data is a nightmare
- When dealing with List/Map , we lose type-safety (especially with typos in Map's key, or refactoring code/structure)
- List<dynamic> and Map<String, dynamic> are not particularly good in terms of performance.

Draft link https://medium.com/@i_2412/flutter-platform-channels-with-protobuf-e895e533dfb7

**Comment by jeroen-meijer** [comment]
Hi there.
Could you specify and give a description of your issue, please?

**Comment by truongsinh** [comment]
Description updated.

**Comment by jeroen-meijer** [comment]
Great!
Please keep it as a draft.
I've added you to the Flutter Community Medium publication as a writer. Please submit the article there so we can review it and schedule it for release.
