### ISSUE TITLE
Package: graphql_client

### ISSUE THREAD

**Issue by truongsinh** [fluttercommunity/community#15]
Dart does not have a decent `graphql_client` at the moment. There are several options:
- (current) https://pub.dartlang.org/packages/graphql_client, which is complicated to use, and does not support raw query
- https://pub.dartlang.org/packages/graphql_flutter, which is tied to Flutter only (thus not usable for CLI, Angular, or others), and lacks of uploading capability

Even though I'm working with both `graphql_flutter` (https://github.com/zino-app/graphql-flutter/pull/195 https://github.com/zino-app/graphql-flutter/pull/202 https://github.com/zino-app/graphql-flutter/pull/203)  and `graphql_client` (https://github.com/orgs/dart-graphql/people), I think it's our best interest for the `graphql_client` and `graphql_flutter` to be included in Flutter Community as well.

**Comment by jeroen-meijer** [comment]
Hi there.
Could you specify and give a description of your issue, please?

**Comment by truongsinh** [comment]
Thanks, description added.

**Comment by jeroen-meijer** [comment]
Thanks. I'm not familiar with GraphQL, so I'll assign somebody else to have a look at this.

**Comment by jeroen-meijer** [comment]
To make things clear, you are suggesting/asking `graphql_client` and `garphql_flutter` to be included into the Flutter Community package library?

**Comment by jeroen-meijer** [comment]
Closing due to lack of reply. Feel free to comment and it can be reopened.
