### ISSUE TITLE
Packages for the community

### ISSUE THREAD

**Issue by letsar** [fluttercommunity/community#16]
Hi,
I don't have the time at the moment to maintain my packages but I don't want to let down the community.
So I'm thinking about transferring some of my packages here and if someone want to maintain them it would be great.
The packages would be:
- https://github.com/letsar/flutter_slidable
- https://github.com/letsar/flutter_staggered_grid_view
- https://github.com/letsar/flutter_parallax
- https://github.com/letsar/flutter_sticky_header
- https://github.com/letsar/kiwi
- https://github.com/letsar/flutter_sidekick

**Comment by jeroen-meijer** [comment]
Hi there,

Thanks for submitting a request for maintainers.
We'll try and find new maintainers as soon as possible.
Right now we don't have a nice way to list packages that need 'adoption' but we'll figure something out.

Thanks again!

This issue will stay open until owners are found.

**Comment by simolus3** [comment]
I'd gladly maintain the kiwi package, if that's ok.

**Comment by jeroen-meijer** [comment]
Hello there.

Thank you for waiting.
I'd like to ask you to follow the transfer guide (found here: https://github.com/fluttercommunity/transfer-guide) for each package you'd like to transfer.
This allows us to keep track of all the packages and find maintainers more easily.

Thank you for your cooperation. If you have any questions, feel free to ask them.

@simolus3 Once the `kiwi` package has been transfered, please submit an issue on this repository to request maintainership.

Closing.
