### ISSUE TITLE
Discussion: Medium alternative

### ISSUE THREAD

**Issue by amreniouinnovent** [fluttercommunity/community#23]
# Discussion: Medium alternative

Should we use an alternative to medium and which alternative?

## Summary
The medium blog is asking for a paid account. I would like to see flutter community articles on a self-hosted website.

Screenshot:
![image](https://user-images.githubusercontent.com/52191652/62022636-429dba80-b1de-11e9-9191-82e8e0b0f47d.png)

**Comment by jeroen-meijer** [comment]
Hi there,

Thanks for bringing this to our attention.
We know of Medium's paywall, and have been looking for an alternative for a while. We haven't found a good one yet, so if you have any suggestions, please tell us here.

As for this article, paywalls are an option set by the author -- we can't turn them off on our end.
Could you link us the article you were reading in here? We'll contact the author to turn the paywall off.

Keeping open for further discussion.
Best regards.

**Comment by amreniouinnovent** [comment]
@jeroen-meijer this is the article link https://medium.com/flutter-community/writing-a-flutter-data-entry-form-app-for-a-rental-agency-e5a7dab20596

But I faced this issue with different authors 

I think alternative could be https://dev.to/

**Comment by Nash0x7E2** [comment]
Good day all, 
Here is a friendly link for the article. Using this link, you should not see the paywall. 
https://medium.com/flutter-community/writing-a-flutter-data-entry-form-app-for-a-rental-agency-e5a7dab20596?source=friends_link&sk=fc334d8d038f83d559dbdfea0abb08b8

- Nash

**Comment by jeroen-meijer** [comment]
We are currently doing research into https://hashnode.com to see if it's a good alternative.

**Comment by amreniouinnovent** [comment]
for future guys use the Opera browser and activate VPN mode
