### ISSUE TITLE
 Is there a way to leave the socket connection open after closing the application?

### ISSUE THREAD

**Issue by arthurlaranjo** [fluttercommunity/community#24]
I have an application where a socket issues an alert when security parameters are exceeded, but when closing the application that connection is terminated and the socket stops issuing the alert. It is of paramount importance to leave this connection open so that the socket will continue to issue alerts even when the application is closed, so that the client has control over these parameters. I would like to know if there is any plugin or some way to leave this connection open even with closed application, either leaving a thread running or something.

**Comment by jeroen-meijer** [comment]
Hi there,

The Flutter Community GitHub is not the place to ask questions regarding issues you face with developing Flutter applications. For those questions, please check out https://flutter.dev/community and use those channels (StackOverflow, Slack, Gitter, etc.).

As for your question; there's no plugin in the Flutter Community GitHub repository to solve your problem to my knowledge. However, Isolates might be able to help you.

Good luck 👋🏻
Closing.
