### ISSUE TITLE
Package Proposal: font_awesome_flutter

### ISSUE THREAD

**Issue by brianegan** [fluttercommunity/community#28]
# Package Proposal: font_awesome_flutter

**Dependency name (as used in *pubspec.yaml*):** font_awesome_flutter
**Current pub.dev Link:** https://pub.dev/packages/font_awesome_flutter
**Description:** The Font Awesome Icon pack available as Flutter Icons. Provides 1500 additional icons to use in your apps.
**Current maintainer:** Brian Egan (@brianegan / brian@brianegan.com)
**Needs new maintainer after transfer:** NO
**Reason for transfer:** The package is a community effort and should reflect that!

**Comment by jeroen-meijer** [comment]
# Approved

Hi there.

Thanks for submitting this package.
It has been reviewed and approved for release on the Flutter Community GitHub! 🎉
Great work. 👍🏻

## What to do next
Please follow **steps 3 through 7** in the [Flutter Community Transfer Guide](https://github.com/fluttercommunity/transfer-guide#3-update-pubspecyaml).

Good luck.

**Comment by jeroen-meijer** [comment]
Hi there 👋🏻

Are there updates on this?

**Comment by brianegan** [comment]
The package has been successfully migrated:

  - https://github.com/fluttercommunity/font_awesome_flutter
  - https://pub.dev/packages/font_awesome_flutter
