### ISSUE TITLE
Encryption and Descyption issue in Flutter and C#

### ISSUE THREAD

**Issue by TejaBalla** [fluttercommunity/community#29]
I am using encryption in Flutter using the link: https://pub.dev/packages/encrypt
Flutter Code is

    final plainText = 'some plain text here';
    final key = encrypt.Key.fromUtf8('16 characters key');
    final iv = IV.fromLength(16);
    final encrypter = Encrypter(AES(key,mode: AESMode.cbc,padding: 'PKCS7'));
    final encrypted = encrypter.encrypt(plainText, iv: iv);
    final decrypted = encrypter.decrypt(encrypted, iv: iv);
    print(decrypted); 
    print(encrypted.base64);

C# code (for decryption)

public static String TestDecrypt(String encryptedText)
{
    var encryptedBytes = Convert.FromBase64String(encryptedText);
    return Encoding.UTF8.GetString(Decrypt(encryptedBytes, GetRijndaelManaged("xxxxxxxxxxxxxxxx")));
}
public static RijndaelManaged GetRijndaelManaged(String secretKey)
{
     var keyBytes = new byte[16];
     var secretKeyBytes = Encoding.UTF8.GetBytes(secretKey);
    Array.Copy(secretKeyBytes, keyBytes, Math.Min(keyBytes.Length, secretKeyBytes.Length));
    return new RijndaelManaged
        {
            Mode = CipherMode.CBC,
            Padding = PaddingMode.PKCS7,
            KeySize = 128,
            BlockSize = 128,
            Key = keyBytes,
            IV = keyBytes
        };
}

I encrypt some plaintext in flutter dart code, But I didn't get proper plain text after decrypting the encrypted text using c# code.

I'm getting a message like below

Padding is invalid and cannot be removed

**Comment by jeroen-meijer** [comment]
Hi there.

`encrypt` is not a Flutter Community package. Please submit bug reports or questions to the repository of the package, the [Flutter Community Gitter chat](https://gitter.im/flutter/flutter) or [StackOverflow](https://stackoverflow.com/questions/tagged/flutter).

Thank you, and good luck with debugging.

Best regards.
Closing.

**Comment by karpediemnow** [comment]
[Solution on stackoverflow ](https://stackoverflow.com/a/62539240/2793017)
