### ISSUE TITLE
Fluttertoast message

### ISSUE THREAD

**Issue by ujas3279** [fluttercommunity/community#32]
Fluttertoast message
i getting following error while add toast message from flutter toast package.

 [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
E/flutter (25624): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)

**Comment by jeroen-meijer** [comment]
Hi there, please submit bug reports to the repository of the package, not /community.

Thank you, and good luck with debugging.

Best regards.
Closing.
