### ISSUE TITLE
Voice activator

### ISSUE THREAD

**Issue by Agbeniga** [fluttercommunity/community#42]
I am working on a voice activated app that makes a sound when I say a code word even when my phone is off. I don't know how to go about it.

**Comment by jeroen-meijer** [comment]
Hi there,

The Flutter Community GitHub is not the place to ask questions regarding issues you face with developing Flutter applications. For those questions, please check out https://flutter.dev/community and use those channels (StackOverflow, Slack, Gitter, etc.).

Good luck 👋🏻
Closing.
