### ISSUE TITLE
SwitchListTile Onchange need to get that button id/name/title

### ISSUE THREAD

**Issue by shaikhfk** [fluttercommunity/community#44]
Sorry if am posting my issue in wrong place do guide me with proper procedure.

I am generating this SwitchListTile in for loop for 5 buttons, but am facing issue in `onChanged` here is there a way to pass  `_onChanged(value, x)` instead of passing static values `_onChanged(value, 8)` 
 to know which button event was invoked? OR is there a way where i can get title of the button whose  `_onChanged();` was invoked.
```
class _DeviceListItemState extends State<DeviceListItem> {
 
  List<SwitchListTile> buttonsList = new List<SwitchListTile>();

  List<Widget> _buildButtonsWithNames(int count) {
buttonsList.add(new SwitchListTile(
      title: Text('Item $i'),
      value: true,
      onChanged: (value) {
        _onChanged(value, 8);
      },
    ));
    return buttonsList;
}
}
```

**Comment by jeroen-meijer** [comment]
Hi there,

The Flutter Community GitHub is not the place to ask questions regarding issues you face with developing Flutter applications. For those questions, please check out https://flutter.dev/community and use those channels (StackOverflow, Slack, Gitter, etc.).

Good luck 👋🏻
Closing.
