### ISSUE TITLE
Showing blank boxes for custom icons

### ISSUE THREAD

**Issue by cloedl** [fluttercommunity/community#46]
Hi everyone,

I am quite new in coding but I like challenges. That's why I'm facing an issue with custom icons.
I wanted specific icons that I could not find so I decided to draw them by myself and save them as .svg. Then I went to the plateform fluttericon.com to convert them as font. On this web site, the icons are showing perfectly.
See below:
![image](https://user-images.githubusercontent.com/62642172/77517529-93a0a400-6e7c-11ea-9b45-c698851e2f66.png)
BUT when I put them into my project, it shows empty boxes
![image](https://user-images.githubusercontent.com/62642172/77517974-48d35c00-6e7d-11ea-9daa-5a16c0c88daa.png)
I did my code as suggested on https://medium.com/flutterpub/how-to-use-custom-icons-in-flutter-834a079d977
In the main.dart file:
![image](https://user-images.githubusercontent.com/62642172/77518750-99978480-6e7e-11ea-8a78-1377e4798209.png)
![image](https://user-images.githubusercontent.com/62642172/77518119-7a4c2780-6e7d-11ea-88d3-f391bb636c30.png)
In the pubspec.yaml file:
![image](https://user-images.githubusercontent.com/62642172/77518171-90f27e80-6e7d-11ea-9d10-44c714571c8c.png)
As I was wondering if the .ttf file was working, I tried the Icons on Word and there they are also working perfectly:
![image](https://user-images.githubusercontent.com/62642172/77518339-ea5aad80-6e7d-11ea-887f-fb45ee17322c.png)
So I really don't know what is not working in my project. I restarted it many time, I did flutter clean, reinstall the app on my emulator, wipe data on the emulator, tried on my own android device (which then show chinese writings instead of the icon), flutter doctor does not show any issues, all the SDKs are uptodate.
Flutter doctor:
`D:\...MyApp\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [version 6.1.7601], locale fr-FR)
    • Flutter version 1.12.13+hotfix.8 at D:\...\MyApp\flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:/.../MyApp/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:/.../MyApp/SDK
    • Java binary at: D:\...\MyApp\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\...\MyApp\Android
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 8.0.0 (API 26) (emulator)

• No issues found!
`
If any has an idea where my problem comes from, I will be pleased to be helped in this way.
Please also let me know if you need more info or if I should present my issue in an other way (I'm quite new here :) )
Have a nice day!

**Comment by jeroen-meijer** [comment]
Hi there,

I understand your question, and I think people from the community will be able to help you out. 😄

The Flutter Community GitHub is not the place to ask questions regarding issues you face with developing Flutter applications. For those questions, please check out https://flutter.dev/community and use those channels (StackOverflow, Slack, Gitter, etc.).

Good luck 👋🏻
Closing.

**Comment by cloedl** [comment]
Hi,

Thank you for your answer. I will have a look there then.
Thanks
