### ISSUE TITLE
Package Proposal: create_atom

### ISSUE THREAD

**Issue by Abhi011999** [fluttercommunity/community#47]
# Package Proposal: create_atom

**Dependency name (as used in *pubspec.yaml*):** create_atom
**Current pub.dev link:** https://pub.dev/packages/create_atom
**Current Git repository link:** https://github.com/Abhi011999/create_atom_flutter
**Description:** An animated widget that displays atom with three electrons revolving around a nucleus at its center.
**Current maintainer:** Abhishek Dubey <[abhi.dubey011999@gmail.com](mailto:abhi.dubey011999@gmail.com)> [@Abhi011999](https://github.com/Abhi011999)
**Needs new maintainer after transfer:** NO (but contributors will be greatly appreciated)
**Reason for transfer:** Contributing to flutter community is as close as i can do to contribute to official flutter. I want this package to become much bigger than it is now, and flutter community will surely help with this purpose and the users will benefit from this package.
**Comments:** I have a good feature roadmap for this package which i will try to implement for a more flexible use of this package.

**Comment by jeroen-meijer** [comment]
Hi there

Thanks for the package request - it looks really cool!
I actually used it on my latest GenericTyping stream, and it was pretty easy to use 😄 
I left some comments in that stream, but need to do a more in-depth review later on.

If you want, you can check out my commentary here: https://youtu.be/d0Vdt70Lbdk?t=4635

I'll let you know once my review is done.
Thanks! 👋🏻

**Comment by Abhi011999** [comment]
Your review is so much appreciated !

My TO-DO for this package -
- Re-factoring and formatting
- In-code documentation
- Removing hard-coded values
- Better implementation for electrons animation

I am glad you like it !!

**Comment by jeroen-meijer** [comment]
Great 👍 
Happy to help!

**Comment by Abhi011999** [comment]
@jeroen-meijer 
I have updated the package. You can do a full review now.

**Note:** There is a breaking change with recent changes so if you're still using the package please checkout the changelog.

**Comment by Abhi011999** [comment]
Looks like there will be no response as the repo seems to be frozen at this time.
So I am closing this issue for now.
