### ISSUE TITLE
Package Proposal: local_google_fonts

### ISSUE THREAD

**Issue by Matt-Gleich** [fluttercommunity/community#48]
# Package Proposal: local_google_fonts

**Dependency name (as used in *pubspec.yaml*):** local_google_fonts
**Current pub.dev link:** https://pub.dev/packages/local_google_fonts#-readme-tab-
**Current Git repository link:** https://github.com/Matt-Gleich/local_google_fonts
**Description:** Define google fonts in your pubspec and automagically add them to you assets and your pubspec
**Current maintainer:** Matthew Gleich, matthewgleich@gmail.com, @Matt-Gleich
**Needs new maintainer after transfer:** NO
**Reason for transfer:** Wanna expose more people to this package as  I think it can help a lot of people.
**Comments:** Excited 😄

**Comment by jeroen-meijer** [comment]
Wow...

This is really cool! 🎉

Thanks for submitting the package request. It's an absolute treat to use! I'd love to have this in the community!

Especially the terminal logging is really useful and so visually pleasing.

```
$ flutter pub run local_google_fonts:main
┗╼╾📄 Reading Config in pubspec.yaml
   ┗╼╾✅ Successfully read config
┗╼╾🔽 Downloading Fonts
   ┗╼╾🔽 Downloading font: Robot
      ┗╼╾❌ Failed to get font: Robot
pub finished with exit code 1

$ flutter pub run local_google_fonts:main
Waiting for another flutter command to release the startup lock...
┗╼╾📄 Reading Config in pubspec.yaml
   ┗╼╾✅ Successfully read config
┗╼╾🔽 Downloading Fonts
   ┗╼╾🔽 Downloading font: Roboto
      ┗╼╾✅ Downloaded Roboto-100i.ttf
      ┗╼╾✅ Downloaded Roboto-300i.ttf
      ┗╼╾✅ Downloaded Roboto-400i.ttf
...
```

## To do before approval

As soon as these issues are fixed, the package will get rereviewed and added to the Flutter Community.

1. **Pubspec formatting and comments.**
Though there is a choice to auto-format (the `format` field), running the tool removes all comments and newlines. I figured this is probably a consequence of the YAML parser you use. Is there a possibility you could preserve comments and newlines?
Alternatively, you could also add an option (something like `output: all/pubspec/terminal/none`, default = `pubspec`) that will overwrite the pubspec (like you do now), output it to the terminal, both or neither. This feature would mitigate the problem, but fixing it altogether would be the best of course.

---

Please make these changes and tell me when you've done so in this issue.
If you have any questions, don't hesitate to ask. 👍🏻

Best regards.

**Comment by Matt-Gleich** [comment]
Thanks! I'll let you know when I've implemented the changes.

**Comment by jeroen-meijer** [comment]
Hello there.

Are there any updates to this?

Thanks!

**Comment by jeroen-meijer** [comment]
No response has been given after a considerable amount of time.
Closing this. Feel free to ask it to be reopened.
