### ISSUE TITLE
Package Proposal: import_sorter

### ISSUE THREAD

**Issue by Matt-Gleich** [fluttercommunity/community#49]
# Package Proposal: import_sorter

**Dependency name (as used in *pubspec.yaml*):** import_sorter
**Current pub.dev link:** https://pub.dev/packages/import_sorter
**Current Git repository link:** https://github.com/Matt-Gleich/import_sorter
**Description:** Dart package that automatically sorts all your flutter or dart imports
**Current maintainer:** Matthew Gleich, matthewgleich@gmail.com, @Matt-Gleich
**Needs new maintainer after transfer:** NO
**Reason for transfer:** Wanna expose more people to this package as I think it can help a lot of people.
**Comments:** Excited 😄

**Comment by jeroen-meijer** [comment]
Awesome!

This is really cool. Especially love the emoji support 😁

## To do before approval

As soon as these issues are fixed, the package will get rereviewed and added to the Flutter Community.

1. **Incompatible with transitive dependencies.**
As an example; in Flutter, you can use `@required` and do `import 'package:meta/meta.dart';` without having `meta` in your dependencies, because `meta` is a transitive dependency of `flutter`. However, running the tool with this condition removes all `meta` imports and creates errors. I was doubting whether this is an actual issue, but transitive dependencies are commonly used, so this tool removing them can be a reason for people to uninstall it (which I wouldn't want because this packages is super sweet).
2. **Unexpected exception when formatting a certain project.**
I tried this tool on a regular Flutter project (with a similar structure to [this project](https://github.com/generictyping/watchlist)). When running the tool on this project, I get the following error:
```
$ flutter pub run import_sorter:main
✅ Formatted /lib/app/assets.dart
✅ Formatted /lib/app/context.dart
✅ Formatted /lib/app/app.dart
✅ Formatted /lib/app/theme.dart
✅ Formatted /lib/utils.dart
✅ Formatted /lib/backend/app_state_store.dart
✅ Formatted /lib/backend/backend.dart
✅ Formatted /lib/backend/utils/observable.dart
✅ Formatted /lib/backend/utils/behaviour_subject.dart
Unhandled exception:
RangeError (index): Invalid value: Not in range 0..11, inclusive: 12
#0      List.[] (dart:core-patch/growable_array.dart:146:60)
#1      sortImports (package:import_sorter/sort.dart:35:14)
#2      main (file:///Users/jeroen/Development/flutter/.pub-cache/hosted/pub.dartlang.org/import_sorter-1.0.7/bin/main.dart:41:38)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```
Unfortunately, this project is currently not open source, so I can't give you the code to test it. However, I'll try to see if I can isolate the issue. Hope this error log gives you any clues. Let me know if you want more info.

---

Please make these changes and tell me when you've done so in this issue.
If you have any questions, don't hesitate to ask. 👍🏻

Best regards.

**Comment by Matt-Gleich** [comment]
Thanks! I'll let you know when I've implemented the changes.

**Comment by Matt-Gleich** [comment]
Thanks! I'll let you know when I've implemented the changes.

**Comment by Matt-Gleich** [comment]
Just resolved the issue with transitive dependencies. I now get the list of all the dependencies from `pubspec.lock` and it even runs `flutter pub get` or `pub get` automatically to ensure the `pubspec.lock` is up to date! 

As far as the error you are getting goes I have no idea why. I tried running it with a similar project and got no error. What it looks like is happening is I am trying to get the value at `i + 1` in a for loop. This shouldn't be a problem though because before that I check in an if statement to see if `i != lines.length`. Here is the code snippet surround this:

```dart
for (int i = 0; i < lines.length; i++) {
    // If line is an import line
    if (lines[i].startsWith('import ') && lines[i].endsWith(';')) {
      if (lines[i].contains('dart:')) {
        dartImports.add(lines[i]);
      } else if (lines[i].contains('package:flutter/')) {
        flutterImports.add(lines[i]);
      } else if (lines[i].contains('package:$package_name/') ||
          !lines[i].contains('package:')) {
        projectImports.add(lines[i]);
      }
      for (final dependency in dependencies) {
        if (lines[i].contains('package:$dependency/') &&
            dependency != 'flutter') {
          packageImports.add(lines[i]);
        }
      }
    } else if (i != lines.length &&
        lines[i].contains('//') &&
        lines[i + 1].startsWith('import ') &&
        lines[i + 1].endsWith(';')) {
    } else if (dartImports.isEmpty &&
        flutterImports.isEmpty &&
        packageImports.isEmpty &&
        projectImports.isEmpty) {
      beforeImportLines.add(lines[i]);
    } else {
      afterImportLines.add(lines[i]);
    }
  }
```

**Comment by jeroen-meijer** [comment]
Great work!

I have good news, I found the culprit. 😄

I have a completely commented out class in that project.

```dart
// import 'package:cloud_firestore/cloud_firestore.dart';
// import 'package:json_annotation/json_annotation.dart';

// class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
//   const TimestampConverter();

//   @override
//   DateTime fromJson(Timestamp value) => value.toDate();

//   @override
//   Timestamp toJson(DateTime value) => Timestamp.fromDate(value);
// }
```

If I remove that, it all formats properly.
I hope that fact and the stack trace I gave you helps resolve the error.
Let me know if I can do anything else! 👋🏻

**Comment by Matt-Gleich** [comment]
Oh cool. Is there anything else I need to do to move forward with the approval process? Thanks!

**Comment by jeroen-meijer** [comment]
The only thing to do is fix the above error, so make sure commented files don't make the tool crash 😊

**Comment by Matt-Gleich** [comment]
Sounds good! Should be done soon

**Comment by jeroen-meijer** [comment]
LGTM

# Approved

Thanks for submitting this package.
It has been reviewed and approved for release on the Flutter Community GitHub! 🎉
Great work. 👍🏻

## What to do next
Please follow **steps 3 through 7** in the [Flutter Community Transfer Guide](https://github.com/fluttercommunity/transfer-guide#3-update-pubspecyaml) and let me know when you're done.

Good luck! 👋🏻

**Comment by Matt-Gleich** [comment]
All ready!

**Comment by jeroen-meijer** [comment]
Great!

# Transfer ownership on pub.dev
You've just been added as a Flutter Community pub.dev publisher member. Please check your email.

Accept the invite, then go to your package and transfer ownership to `fluttercommunity.dev`
<img width="760" alt="image" src="https://user-images.githubusercontent.com/14292245/80212853-8cfe7b80-8638-11ea-8c29-cf6eaa3d6a3b.png">

# Transfer the package to GitHub

You have also been invited to be a member of the Flutter Community GitHub repository. After accepting your invitation, please go to your repository's settings and transfer the package to the user/organisation `fluttercommunity`.
<img width="767" alt="image" src="https://user-images.githubusercontent.com/14292245/80213099-f54d5d00-8638-11ea-8fd4-f939a9b55384.png">


Let me know if you have any questions or need help! 👍🏻

**Comment by Matt-Gleich** [comment]
I am getting a `You don’t have the permission to create public repositories on fluttercommunity` error when trying to transfer the repo.

**Comment by jeroen-meijer** [comment]
Sorry about that! We recently changed our member permission system. Please try again.

**Comment by Matt-Gleich** [comment]
Done! For some reason, I am not able to change the description of the repo. I saw that some other repos had `Maintainer: @Matt-Gleich` in their description. Can you please enable that for me? Thanks!

**Comment by jeroen-meijer** [comment]
Awesome. That's the next step! Let me fix that for you.

**Comment by jeroen-meijer** [comment]
Done! You should have access to maintain anything on the repo now.

Let me know if you have any remaining questions.
Thanks for the package! 👋🏻

Closing this.

**Comment by Matt-Gleich** [comment]
Thanks!

**Comment by jeroen-meijer** [comment]
PS: Your package will show up on our package table soon. 👍🏻

**Comment by jeroen-meijer** [comment]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/14292245/80284458-e2ad5380-871e-11ea-85bc-8bbada140309.png">

Tada~ 🎉
