### ISSUE TITLE
Package Proposal: flutter_workmanager

### ISSUE THREAD

**Issue by petermnt** [fluttercommunity/community#54]
# Package Proposal: flutter_workmanager

**Dependency name (as used in *pubspec.yaml*):** flutter_workmanager
**Current pub.dev link:** https://pub.dev/packages/workmanager
**Current Git repository link:** https://github.com/vrtdev/flutter_workmanager
**Description:** Flutter wrapper for Android WorkManager (and iOS background task), allowing for background work in dart
**Current maintainer:** Peter Menten, digitalemedia.vrt@gmail.com, petermnt / vrtdev
**Needs new maintainer after transfer:** YES
**New maintainer (if applicable):** 
**Reason for transfer:** We no longer have the capacity to maintain this plugin
**Comments:**

**Comment by jeroen-meijer** [comment]
This package has been approved immediately because a new maintainer needs to be found, so our transfer window is short.

The pub scores indicate the package is overall well-built, so any changes that need to happen after a new maintainer has been found will most probably be very minimal.

**Comment by slightfoot** [comment]
We have approved the transfer. We have moved the github repo and transferred ownership on pub.dev. We still need to update the readme and other resources and publish the package again.

**Comment by shaun0203** [comment]
I dont mind helping where ever needed.

**Comment by jeroen-meijer** [comment]
Closing this as it seems finished.

@slightfoot If it doesn't please list the last TODOs here and feel free to reopen the issue.
