### ISSUE TITLE
Requesting GitHub Pages: backdrop

### ISSUE THREAD

**Issue by daadu** [fluttercommunity/community#55]
# Requesting GitHub Pages: backdrop

**Flutter Community repository link:** https://github.com/fluttercommunity/backdrop

Add `gh-pages` branch on the repo as GitHub Pages from Settings

**Comment by daadu** [comment]
I do not want Travis access, just want to configure github pages

**Comment by daadu** [comment]
@jeroen-meijer Reminder for the request.

**Comment by jeroen-meijer** [comment]
Thanks for the reminder! I'll get to this this weekend 👍🏻

**Comment by jeroen-meijer** [comment]
Well, that got delayed...

@daadu Apologies for the long delay. 😞 
I've been gone for a while, but am currently handling all open community issues.

I've set up GitHub pages on the `gh-pages` branch on the root folder, and it's now hosted at https://fluttercommunity.github.io/backdrop/. 👍🏻 

I've also given you the `Maintainer` role on the backdrop repo, so hopefully you can manage all these settings yourself.
Let me know if you can't access the settings you need, or if anything else needs to happen!

Thanks, and apologies again.

Best regards.

**Comment by daadu** [comment]
@jeroen-meijer Thanks.
