### ISSUE TITLE
Package Proposal: flutter_uploader

### ISSUE THREAD

**Issue by ened** [fluttercommunity/community#56]
# Package Proposal: flutter_uploader

**Dependency name (as used in *pubspec.yaml*):** flutter_uploader
**Current pub.dev link:** https://pub.dev/packages/flutter_uploader
**Current Git repository link:** https://github.com/BlueChilli/flutter_uploader
**Description:** A plugin for creating and managing upload tasks. Supports iOS and Android.
**Current maintainer:** Max, onikiri2007@gmail.com, @onikiri2007
**Needs new maintainer after transfer:** yes
**New maintainer (if applicable):** Sebastian, sebastian.roth@gmail.com, @ened
**Reason for transfer:** Quicker release cycles and steady maintenance for upcoming versions, current maintainer contacted & approved of transfer
**Comments:**

**Comment by ened** [comment]
@jeroen-meijer How are you doing? Is there anything else needed to get this one included?

**Comment by jeroen-meijer** [comment]
Hi there @ened! 👋🏻 

Apologies, I've been gone for a while but am currently reviewing all open packages.

The information you have provided should be enough for now, thank you!
I'll be in contact if any updates occur.

Thank again.

**Comment by jeroen-meijer** [comment]
Hi there @ened 

I've taken a look at your package on [pub.dev](https://pub.dev/packages/flutter_uploader/score) and it looks like it has about 91% popularity (nice!) and 70/110 pub points.

Before reviewing it, I'd like to ask you to update the package to get full marks (points) on the following criteria:
- Follow Dart file conventions
- Provide documentation
- Pass static analysis

After you have done so, please update the package both on GitHub and pub.dev and send me a message in this thread.

Thank you in advance.
If you need any help or have any questions, please let me know.

Good luck! 😄

**Comment by ened** [comment]
@jeroen-meijer - a per-release has been pushed to pub here: https://pub.dev/packages/flutter_uploader/versions/2.0.0-beta.1
Does that qualify or do you require a full, stable, release?

**Comment by jeroen-meijer** [comment]
The pre-release is fine! I'll take a look later today. Thanks for the quick response!

**Comment by jeroen-meijer** [comment]
Hi there @ened

Awesome work!
The package works great, docs looks good and the example is really useful well-built. 👏🏻 

I'd love to have this in the community repo!

# Approved

Thanks for submitting this package.
It has been reviewed and approved for release on the Flutter Community GitHub! 🎉
Great work. 👍🏻

## What to do next
Please follow **steps 3 through 7** in the [Flutter Community Transfer Guide](https://github.com/fluttercommunity/transfer-guide#3-update-pubspecyaml) and let me know when you're done.

Good luck! 👋🏻

**Comment by onikiri2007** [comment]
Hi @jeroen-meijer 
steps 3 through 7 in the Flutter Community Transfer Guide has been completed.

cheers

**Comment by jeroen-meijer** [comment]
Great!

# Transfer ownership on pub.dev
You've just been added as a Flutter Community pub.dev publisher member. Please check your email (sebastian.roth@gmail.com).

Accept the invite, then go to your package and transfer ownership to `fluttercommunity.dev`
<img width="760" alt="image" src="https://user-images.githubusercontent.com/14292245/80212853-8cfe7b80-8638-11ea-8c29-cf6eaa3d6a3b.png">

# Transfer the package to the organization

You have also been invited to be a member of the Flutter Community GitHub organization. After accepting your invitation, please go to your repository's settings and transfer the package to the user/organization `fluttercommunity`.
<img width="767" alt="image" src="https://user-images.githubusercontent.com/14292245/80213099-f54d5d00-8638-11ea-8fd4-f939a9b55384.png">


Let me know if you have any questions or need help! 👍🏻

**Comment by ened** [comment]
@jeroen-meijer Those two steps have been done as well!

**Comment by jeroen-meijer** [comment]
Great! Looks like almost everything is in place. Well done. 👏🏻 

I checked out the pubspec and see that in the maintainer field you have your GitHub handle as `<@ened>` but we require you to use parentheses `(@ened)`. Could you make that adjustment? (You might need to push a new pub version after making that change, as well.)

**Comment by ened** [comment]
@jeroen-meijer is it possible to enable Cirrus CI on the fluttercommunity organization? Normally, PRs like the one linked will show a few checks.

**Comment by ened** [comment]
@jeroen-meijer `2.0.0-beta.3` has been published

**Comment by jeroen-meijer** [comment]
LGTM 👍🏻

I've added Cirrus CI to the repo. Let me know if you need anything else, and feel free to reopen this.

Thank again! Hope that's everything.
Closing.
