### ISSUE TITLE
Discussion: Workmanager

### ISSUE THREAD

**Issue by ened** [fluttercommunity/community#63]
# Discussion: Workmanager

Currently, `workmanager` is without a maintainer.
As our company is relying on the plugin's stability, I'd like to offer to maintain this package (and hopefully bring it to 1.0.0).
The isolate/background work in `flutter_uploader` is similar to `workmanager` - so a lot of knowledge can be shared.

**Comment by mhadaily** [comment]
Hello @ened 

it would be nice, I have given access to the repo, please take care of the package until we get a response from the maintainer or decide what to do next.

**Comment by Maxiggapp** [comment]
Hello Majid,
Thanks a lot. The repo is open now.
I will waiting what’s next great idea.

Greetings, Guido

**Comment by ened** [comment]
Thank you all - I have the permissions now and will get to work!
