### ISSUE TITLE
Flutter starter kit 

### ISSUE THREAD

**Issue by KingWu** [fluttercommunity/community#7]
Hi,
i just write a flutter starter kit for beginner to demo how to use Bloc pattern, RxDart, sqflite, Fluro and Dio to architect a flutter project. This starter kit build an App Store app as a example.

https://github.com/KingWu/flutter_starter_kit

Thanks.

**Comment by jeroen-meijer** [comment]
It's been a while and got no response, so I'll close this.
Feel free to ask for it to be reopened.
