### ISSUE TITLE
Establish a standard for package README

### ISSUE THREAD

**Issue by modulovalue** [fluttercommunity/community#8]
I really like the idea of collecting useful flutter packages in a central place.
I'd like to make a suggestion that the README's of flutter community packages should follow a common template because most of the time I still end up on Dart Pub because the README is missing essential information. 

Example: 

- Flutter community header image at the top,
- A title
- Link or badge to the dart pub page
- A short description.
- Dropdown with installation instructions.
- Dropdown with a simple example
- Everything else
- License

And by dropdown I mean something like this.

<details>
<summary>Dropdown? (click me)</summary>
Dropdown!
</details>
<br>

I believe that this would save the developers and users a lot of time.

**Comment by jeroen-meijer** [comment]
Hi there, sorry for the late reply.

Very good suggestion!
I really want to make this happen. I’ll talk to the team and we’ll take your template into consideration.

If it’s implemented we’ll (most likely) update the community/README file to include the instructions. I’ll let you know here once it’s done.

Thanks again.

**Comment by jeroen-meijer** [comment]
Hi there.

I wanted to tell you that with the recently released transfer guide (found here: https://github.com/fluttercommunity/transfer-guide), we've made an effort to improve the general look of all the new README files coming in. We'll see how we can "enforce" a better README onto all repositories.

Thanks again for your suggestion.
Closing this.

Best regards.
