### ISSUE TITLE
Package Maintainer Application: flutter_google_places

### ISSUE THREAD

**Issue by juliansteenbakker** [fluttercommunity/community#84]
# Package Maintainer Application: flutter_google_places

It doesn't seem like flutter_google_places has any active maintainer. This is also mentioned in the description of the repository

I would like to help maintain this package as i will need it for my own application. There are several fixes available for this and some people even started their own fork because of low maintenance.

I would also like to point out that i already made another application for https://github.com/fluttercommunity/community/issues/76 flutter_wear_os which hasn't received any feedback yet. (@slightfoot, @jeroen-meijer) It seems like overall activity on some fluttercommunity plugins is low.

**Comment by jeroen-meijer** [comment]
Assigning @mhadaily since he delegates these kinds of tasks these days. If anybody needs me, feel free to reach out 😄

**Comment by juliansteenbakker** [comment]
> If anybody needs me, feel free to reach out 😄

Thanks for the quick response! I was looking trough some of the plugins that are available under the fluttercommunity organisation and it seems that there are multiple packages that don't have a lot of activity and i was thinking, isn't it better to create a general repository like the plus_plugins repository, but called something like community_plugins, and put all these packages in there? It would be a lot easier from a maintainers perspective, and I think it would also boost the visibility and quality of these packages. We can also enable some CI checks just like the plus_plugins have.

**Comment by mhadaily** [comment]
@juliansteenbakker welcome to https://github.com/fluttercommunity/flutter_google_places as maintainer. 
I hope you can make this package even better, please start with issues and bug fixes.

To release, the package on pub.dev, I will assist for a while, we are working on a new bot to take care of releasing until then, I will help to release, I will invite you to our slack to discuss more.
