### ISSUE TITLE
Package Proposal: Chewie

### ISSUE THREAD

**Issue by brianegan** [fluttercommunity/community#87]
# Package Proposal: Chewie

**Dependency name (as used in *pubspec.yaml*):** chewie
**Current pub.dev link:** https://pub.dev/packages/chewie
**Current Git repository link:** https://github.com/brianegan/chewie
**Description:** Video player
**Current maintainer:** Rebar Ahmad, @Ahmadre 
**Needs new maintainer after transfer:** NO
**Reason for transfer:** The community has done a fantastic job maintaining the package for a while now. I'd like to transfer it to the proper FC org so the maintainers have full control over the repo!

**Comment by brianegan** [comment]
Any thoughts on this one? Lots of folks use Chewie, and it could use a proper home with more community ownership.

**Comment by jeroen-meijer** [comment]
@brianegan Thanks for flagging this! Definitely a great one to have under our wing.

Pinging @mhadaily since he's head of GH atm :)

**Comment by brianegan** [comment]
Thanks!

**Comment by mhadaily** [comment]
Hi @brianegan definitely good one. I can facilitate moving this repo to FC however, my question to you, will Rebar Ahmad, @Ahmadre still maintain this repo or we should look for a new maintainer?

**Comment by brianegan** [comment]
Thanks @mhadaily -- I'd certainly leave that question up to @ahmadre. If he's doesn't have the time or interest, I've received messages from a couple other contributors I could reach out to as well.

**Comment by mhadaily** [comment]
That would be fantastic. 

Let's figure out about the maintainers and then we can transfer the package.

**Comment by diegotori** [comment]
@brianegan if you want, I can also volunteer my time for maintaining Chewie as well, in terms of cutting new releases to pub.dev (since I also release the reorderables library to there as well), and reviewing code. Feel free to reach out since my email's in my GitHub profile.

**Comment by diegotori** [comment]
@brianegan Any word on whether or not @Ahmadre will still maintain Chewie going forward? Otherwise, I think it would make sense to add some provisional maintainers to at least finalize the transition. Thank you in advance.

**Comment by brianegan** [comment]
Thanks @diegotori. Since we haven't heard from Rebar, would you like to be named as the maintainer of the package?

**Comment by diegotori** [comment]
@brianegan Any word on whether we have another maintainer on board aside from myself? Thanks in advance.

**Comment by brianegan** [comment]
@diegotori Unfortunately not. Perhaps @cbenhagen or @maherjaafar would like to be co-maintainers? Are there any companies folks know of that use Chewie and would want to sponsor maintainers?

**Comment by maherjaafar** [comment]
Hi @brianegan, thanks for mentioning me to be co-maintainer for this package. 
Yes, I can help out to maintain this package. 🙌

**Comment by brianegan** [comment]
Thanks @maherjaafar -- In that case, it looks like we have two maintainers for the package: @diegotori and @maherjaafar. 

@mhadaily Please let me know what the next steps are :) I believe I'm an admin of the FC github organization and can transfer the repo when it makes sense.

**Comment by mhadaily** [comment]
@brianegan , if you are ok now, please go ahead and transfer the package, assign new maintainers and let me know when it's done. 
Please make sure you or anyone else that has already access to pub.dev, can continue publishing until our new platform is ready for publishing the package which doesn't require a maintainer to get access to pub.dev.

**Comment by brianegan** [comment]
I've transferred the package on Github and set Fluttercommunity.dev as the publisher on pub.dev. Unfortunately, I didn't realize making that change on pub.dev would also remove my ability to add @diegotori and @maherjaafar as uploaders. 

Sorry if I messed that part up :/

**Comment by brianegan** [comment]
I was able to add @diegotori to the list of uploaders for the FlutterCommunity organization on pub.dev.

At this point, I think everything is set up so that @diegotori and @maherjaafar can take over as maintainers! Only @diegotori can publish new versions for now, but it sounds like @mhadaily and company have a plan to make it easier in the future :)

Thanks everyone for helping out. Long live Chewie!

**Comment by mhadaily** [comment]
Great, Feel free to close this comment @brianegan if all is done

**Comment by diegotori** [comment]
@brianegan Thank you very much for making this all happen. I will definitely start the first update to pub.dev tonight.
